### ISSUE TITLE
LaTeX 公式渲染以及图像篡改检测工作交流

### ISSUE THREAD

**Issue by jstacer1** [greatzh/Papers#2]
<https://github.com/greatzh/Papers/blob/main/image-forgery/2023/tbformer.md> 显示有问题

**Comment by jstacer1** [comment]
非常棒的知识库，相见恨晚！

**Comment by jstacer1** [comment]
[Towards Robust Tampered Text Detection in Document Image: New dataset and New Solution ](https://openaccess.thecvf.com/content/CVPR2023/papers/Qu_Towards_Robust_Tampered_Text_Detection_in_Document_Image_New_Dataset_CVPR_2023_paper.pdf)这篇文章您可以看看，[提供了新数据集](https://github.com/qcf-568/DocTamper) 我目前研1，打算做这个方向，非常希望和您交流

**Comment by greatzh** [comment]
年初的时候我也看到了阿里天池有相关的比赛，应该是 ICDAR 2023 DTT in Images，有机会我会把相关的论文更新一下。

**Comment by jstacer1** [comment]
> 年初的时候我也看到了阿里天池有相关的比赛，应该是 ICDAR 2023 DTT in Images，有机会我会把相关的论文更新一下。

对的，不过这篇论文中的doctamper数据集并不是 ICDAR 2023 DTT in Images比赛的数据集，但是这篇论文作者是天池ICDAR23文本图像篡改检测竞赛冠军

**Comment by jstacer1** [comment]
> 年初的时候我也看到了阿里天池有相关的比赛，应该是 ICDAR 2023 DTT in Images，有机会我会把相关的论文更新一下。

希望您能看一下这篇，我是研1小白，不知道该从哪些方面改进这篇论文，之前对Image Forgery Detection and Localization这个领域也不熟悉，但是本质上这篇论文中的task是Image Forgery Detection and Localization的子集，论文作者也复现过一些Image Forgery Detection and Localization的模型在doctamper测试过

**Comment by greatzh** [comment]
> [https://github.com/greatzh/Papers/blob/main/image-forgery/2023/tbformer.md](url)显示有问题

谢谢你的报告，看起来是LaTeX公式的问题，稍后我会修改一下。

**Comment by greatzh** [comment]
> 希望您能看一下这篇，我是研1小白，不知道该从哪些方面改进这篇论文，之前对Image Forgery Detection and Localization这个领域也不熟悉，但是本质上这篇论文中的task是Image Forgery Detection and Localization的子集，论文作者也复现过一些Image Forgery Detection and Localization的模型在doctamper测试过

这个我也很难一下子给出什么有用的建议怎么去改进这篇论文，范围有点大。如果是新方法，我看到最近一些做图像篡改检测的都在用对比学习来做，大概可以试试；新任务就尝试加一些限制吗？看到在公共数据集上的表现都已经0.99了，看看是不是可以提出个数据集什么的。

**Comment by jstacer1** [comment]
> > 希望您能看一下这篇，我是研1小白，不知道该从哪些方面改进这篇论文，之前对Image Forgery Detection and Localization这个领域也不熟悉，但是本质上这篇论文中的task是Image Forgery Detection and Localization的子集，论文作者也复现过一些Image Forgery Detection and Localization的模型在doctamper测试过
> 
> 这个我也很难一下子给出什么有用的建议怎么去改进这篇论文，范围有点大。如果是新方法，我看到最近一些做图像篡改检测的都在用对比学习来做，大概可以试试；新任务就尝试加一些限制吗？看到在公共数据集上的表现都已经0.99了，看看是不是可以提出个数据集什么的。

公共数据集上的表现都已经0.99了(这是tsroie数据集比较小总共就986张)，doctamper是他提出来的有170,000，很大了，f1值只有0.792，自己创一个数据集感觉就没啥意义，目标是发一篇ccf b，对于您说的图像篡改检测的都在用对比学习来做，但如果我投稿的话，因为这个文本图像篡改检测没啥人做，会不会就送给一些Image Forgery Detection and Localization这个领域的审稿人，然后就觉得这个task其实就是Image Forgery Detection and Localization的子领域，方法也不够novel。。。

**Comment by greatzh** [comment]
我想它的确是图像篡改检测的一部分，只不过图像是文本图像；但我
认为应该不会因为一个大的概念，用对比学习，或者说是用transformer，就被认为没有创新，因为也不是完全把ifdl的方法直接套在dtt的任务上，大部分时候novel的问题应该还是看你怎么讲好故事。

**Comment by jstacer1** [comment]
> 我想它的确是图像篡改检测的一部分，只不过图像是文本图像；但我 认为应该不会因为一个大的概念，用对比学习，或者说是用transformer，就被认为没有创新，因为也不是完全把ifdl的方法直接套在dtt的任务上，大部分时候novel的问题应该还是看你怎么讲好故事。

感谢解惑，后续再与您交流

**Comment by jstacer1** [comment]
> 我想它的确是图像篡改检测的一部分，只不过图像是文本图像；但我 认为应该不会因为一个大的概念，用对比学习，或者说是用transformer，就被认为没有创新，因为也不是完全把ifdl的方法直接套在dtt的任务上，大部分时候novel的问题应该还是看你怎么讲好故事。

[Progressive Supervision for Tampering Localization in Document Images](https://link.springer.com/chapter/10.1007/978-981-99-8184-7_11)这篇 ICONIP2023 也可以看看

**Comment by jstacer1** [comment]
> > 希望您能看一下这篇，我是研1小白，不知道该从哪些方面改进这篇论文，之前对Image Forgery Detection and Localization这个领域也不熟悉，但是本质上这篇论文中的task是Image Forgery Detection and Localization的子集，论文作者也复现过一些Image Forgery Detection and Localization的模型在doctamper测试过
> 
> 这个我也很难一下子给出什么有用的建议怎么去改进这篇论文，范围有点大。如果是新方法，我看到最近一些做图像篡改检测的都在用对比学习来做，大概可以试试；新任务就尝试加一些限制吗？看到在公共数据集上的表现都已经0.99了，看看是不是可以提出个数据集什么的。

对比学习文章有哪些呢，我在project里面没有看到，最好是代码的

**Comment by greatzh** [comment]
感谢您的分享，您提到的文章已经添加到了新的分类下，<https://github.com/greatzh/Papers#tamper-text-in-detection>。

同时，此前您报告的 <https://github.com/greatzh/Papers/blob/main/image-forgery/2023/tbformer.md>  存在的报错已经解决，但 GitHub 采用的是 MathJax，因此还有一些公式渲染失败。

关于应用对比学习到篡改检测中的文章，仓库中此前有添加来自 ICCV 2023 的工作，<https://github.com/Knightzjz/NCL-IML>。

**Comment by jstacer1** [comment]
> 感谢您的分享，您提到的文章已经添加到了新的分类下，<https://github.com/greatzh/Papers#tamper-text-in-detection>。
> 
> 同时，此前您报告的 <https://github.com/greatzh/Papers/blob/main/image-forgery/2023/tbformer.md> 存在的报错已经解决，但 GitHub 采用的是 MathJax，因此还有一些公式渲染失败。
> 
> 关于应用对比学习到篡改检测中的文章，仓库中此前有添加来自 ICCV 2023 的工作，<https://github.com/Knightzjz/NCL-IML>。

对于 <https://github.com/greatzh/Papers/blob/main/image-forgery/2023/tbformer.md>中的思考部分您提出的问题是“noise map对copy move其实是没有用的，以及说整个的frequency”，这是为什么呢？另外高低频结合的文章哪些呢？

**Comment by greatzh** [comment]
因为我认为用噪声来辅助，只对不同图片的篡改会起到作用，像 splicing 用 noise map 就可以，而 copy move 是在同一张图片上进行操作，复制的部分通常保留了原始图像的结构和特征，很难引起显著性变化，所以用噪声作用并不大。

频率信息是因为目前大部分都在用高频信息，而高频，又对应着图像中变化较快的部分，其中包括噪声、边缘和细节等。所以我才会认为噪声就是集中在高频信息里，它的引入对 copy move 的作用不大。当然，频率信息不只是说噪声，噪声可以在各个频率范围内存在，frequency 用在copy move 上应该还是有一些工作的。

高频低频结合的论文我也不太记得了，也可能是我看的在人脸的篡改中看到的，大概只是印象中 multi-frequency 有很多的工作。
